const dadosCandidaturas = [
  {
    id: "1",
    empresa: "TechCorp Canadá",
    cargo: "Software Engineer (React/Node)",
    dataPublicacao: "01/05/2026",
    dataAplicacao: "10/05/2026",
    status: "Entrevista Técnica",
    localizacao: "Toronto, ON (Remoto)",
    salario: "CAD 85.000/ano",
    descricao:
      "Atuar no desenvolvimento e manutenção de plataformas escaláveis em nuvem, migrando sistemas legados para arquiteturas modernas baseadas em microsserviços.",
    requisitos: ["React Native", "Node.js", "Inglês Fluente", "Docker"],
    feedback:
      "Aprovado na triagem inicial. Teste técnico agendado para o dia 20/05.",
  },
  {
    id: "2",
    empresa: "Banco Central do Brasil",
    cargo: "Analista de TI (Concurso)",
    dataPublicacao: "10/02/2026",
    dataAplicacao: "15/04/2026",
    status: "Em análise",
    localizacao: "Brasília, DF",
    salario: "R$ 21.000/mês",
    descricao:
      "Cargo público focado em modernização de sistemas financeiros e segurança da informação.",
    requisitos: [
      "Aprovação em concurso público",
      "Java",
      "SQL",
      "Arquitetura de Software",
    ],
    feedback: "Aguardando publicação do edital e resultado da prova objetiva.",
  },
  {
    id: "3",
    empresa: "Fintech Brasil",
    cargo: "Desenvolvedor Front-end Pleno",
    dataPublicacao: "15/05/2026",
    dataAplicacao: "28/05/2026",
    status: "Rejeitado",
    localizacao: "São Paulo, SP (Híbrido)",
    salario: "R$ 8.500/mês",
    descricao:
      "Criação de interfaces responsivas para o novo aplicativo de investimentos da empresa.",
    requisitos: [
      "React",
      "TypeScript",
      "Styled Components",
      "Testes Unitários",
    ],
    feedback:
      "Infelizmente decidimos seguir com candidatos que possuíam mais experiência em mercado financeiro.",
  },
  {
    id: "4",
    empresa: "Global Solutions",
    cargo: "Desenvolvedor Full Stack",
    dataPublicacao: "25/05/2026",
    dataAplicacao: "02/06/2026",
    status: "Enviada",
    localizacao: "Remoto",
    salario: "A combinar",
    descricao:
      "Vaga para atuar em projetos internacionais, colaborando com equipes nos EUA e Europa para entrega de soluções ágeis.",
    requisitos: [
      "JavaScript",
      "PostgreSQL",
      "Metodologias Ágeis (Scrum)",
      "Inglês Intermediário",
    ],
    feedback: "Inscrição confirmada.",
  },
  {
    id: "5",
    empresa: "Startup Inovadora",
    cargo: "Engenheiro de Software Júnior",
    dataPublicacao: "01/03/2026",
    dataAplicacao: "10/03/2026",
    status: "Aprovado",
    localizacao: "Salvador, BA",
    salario: "R$ 5.500/mês",
    descricao:
      "Fazer parte do time fundacional da startup, construindo o MVP do produto do zero até o lançamento.",
    requisitos: [
      "Lógica de Programação",
      "React Native",
      "Firebase",
      "Vontade de aprender",
    ],
    feedback: "Oferta aceita! Início programado para o próximo mês.",
  },
  {
    id: "6",
    empresa: "Maple Leaf Tech",
    cargo: "Senior Frontend Engineer",
    dataPublicacao: "05/05/2026",
    dataAplicacao: "20/05/2026",
    status: "Banco de Talentos",
    localizacao: "Vancouver, BC (Relocation)",
    salario: "CAD 110.000/ano",
    descricao:
      "Liderar a equipe de front-end na reconstrução do portal principal de e-commerce utilizando as tecnologias mais recentes do ecossistema React.",
    requisitos: [
      "React",
      "Next.js",
      "GraphQL",
      "Inglês Avançado",
      "Liderança Técnica",
    ],
    feedback:
      "Gostamos muito do seu perfil! A vaga atual foi congelada, mas manteremos seu contato para oportunidades futuras no próximo trimestre.",
  },
  {
    id: "7",
    empresa: "AgroTech Oeste",
    cargo: "Desenvolvedor Mobile Pleno",
    dataPublicacao: "05/06/2026",
    dataAplicacao: null,
    status: "Vaga Divulgada",
    localizacao: "Luís Eduardo Magalhães, BA (Híbrido)",
    salario: "R$ 7.200/mês",
    descricao:
      "Desenvolvimento de aplicativo de monitoramento de safra e logística agrícola para produtores da região.",
    requisitos: [
      "React Native",
      "Geolocalização/Maps",
      "Consumo de APIs REST",
      "SQLite",
    ],
    feedback: "Seja um dos primeiros a se candidatar!",
  },
  {
    id: "8",
    empresa: "TCU - Tribunal de Contas da União",
    cargo: "Auditor Federal de Controle Externo (TI)",
    dataPublicacao: "15/12/2025",
    dataAplicacao: "20/01/2026",
    status: "Aprovado",
    localizacao: "Brasília, DF",
    salario: "R$ 23.000/mês",
    descricao:
      "Auditoria de sistemas governamentais, análise de dados complexos e garantia da segurança da informação no setor público.",
    requisitos: [
      "Nível Superior",
      "Conhecimento em Banco de Dados",
      "Legislação Pública",
      "Segurança da Informação",
    ],
    feedback: "Nomeação publicada no Diário Oficial. Aguardando posse.",
  },
  {
    id: "9",
    empresa: "Silicon Valley Startups",
    cargo: "React Native Mobile Dev",
    dataPublicacao: "01/06/2026",
    dataAplicacao: null,
    status: "Vaga Divulgada",
    localizacao: "San Francisco, CA (100% Remoto)",
    salario: "USD 5.000/mês",
    descricao:
      "Estamos buscando um desenvolvedor focado em mobile para criar features de alta performance em nosso aplicativo de health-tech.",
    requisitos: [
      "React Native CLI",
      "Animações (Reanimated)",
      "Zustand/Redux",
      "Inglês Comunicativo",
    ],
    feedback: "Candidaturas abertas até 15/07.",
  },
  {
    id: "10",
    empresa: "SEFAZ",
    cargo: "Auditor Fiscal (Tecnologia da Informação)",
    dataPublicacao: "20/05/2026",
    dataAplicacao: "05/06/2026",
    status: "Enviada",
    localizacao: "Salvador, BA",
    salario: "R$ 19.500/mês",
    descricao:
      "Desenvolvimento e manutenção do sistema de emissão de notas fiscais eletrônicas e cruzamento de dados tributários.",
    requisitos: [
      "Java",
      "Oracle DB",
      "Arquitetura Orientada a Eventos",
      "Direito Tributário Básico",
    ],
    feedback: "Inscrição confirmada.",
  },
  {
    id: "11",
    empresa: "Nubank",
    cargo: "Engenheiro de Software Pleno",
    dataPublicacao: "18/05/2026",
    dataAplicacao: "25/05/2026",
    status: "Fit Cultural",
    localizacao: "São Paulo, SP (Remoto)",
    salario: "R$ 11.000/mês",
    descricao:
      "Fazer parte do esquadrão de cartões de crédito, focando na escalabilidade e disponibilidade dos serviços transacionais.",
    requisitos: [
      "Clojure ou vontade de aprender",
      "Arquitetura de Microsserviços",
      "Cultura Ágil",
      "Testes Automatizados",
    ],
    feedback: "Aprovado no live coding. Entrevista com a liderança agendada.",
  },
  {
    id: "12",
    empresa: "Mercado Livre",
    cargo: "Desenvolvedor Frontend (React)",
    dataPublicacao: "04/06/2026",
    dataAplicacao: null,
    status: "Vaga Divulgada",
    localizacao: "Osasco, SP (Híbrido)",
    salario: "R$ 9.800/mês",
    descricao:
      "Atuar na evolução do painel de vendedores do Mercado Pago, garantindo uma interface rápida e acessível.",
    requisitos: [
      "React",
      "Acessibilidade (a11y)",
      "Performance Web",
      "Design Systems",
    ],
    feedback: "Candidate-se e participe do nosso processo seletivo unificado.",
  },
  {
    id: "13",
    empresa: "IBGE",
    cargo: "Supervisor de Coleta e Qualidade",
    dataPublicacao: "05/01/2026",
    dataAplicacao: "10/02/2026",
    status: "Em análise",
    localizacao: "Nacional",
    salario: "R$ 3.100/mês",
    descricao:
      "Supervisionar o trabalho de coleta de dados em campo, garantindo a qualidade e veracidade das informações censitárias.",
    requisitos: [
      "Ensino Médio/Superior",
      "CNH Categoria AB",
      "Disponibilidade para viagens",
      "Organização",
    ],
    feedback: "Análise de recursos da prova objetiva em andamento.",
  },
  {
    id: "14",
    empresa: "DevSolutions Agency",
    cargo: "Full Stack Developer",
    dataPublicacao: "20/04/2026",
    dataAplicacao: "02/05/2026",
    status: "Rejeitado",
    localizacao: "Remoto",
    salario: "R$ 6.000/mês",
    descricao:
      "Agência de desenvolvimento ágil buscando profissional para atuar em múltiplos projetos simultâneos de clientes diversos.",
    requisitos: ["React", "Node.js", "PHP", "AWS Básica"],
    feedback: "Buscamos alguém com perfil mais voltado para PHP neste momento.",
  },
  {
    id: "15",
    empresa: "HealthApp Inc",
    cargo: "Mobile Developer (React Native)",
    dataPublicacao: "03/06/2026",
    dataAplicacao: null,
    status: "Vaga Divulgada",
    localizacao: "Nova York, NY (Remoto)",
    salario: "USD 4.500/mês",
    descricao:
      "Criação de módulos de telemedicina e agendamento de consultas para nosso aplicativo principal.",
    requisitos: [
      "React Native",
      "WebRTC",
      "Integração com APIs de Saúde",
      "Inglês Avançado",
    ],
    feedback: "Estamos expandindo nosso time LATAM.",
  },
  {
    id: "16",
    empresa: "Itaú Unibanco",
    cargo: "Engenheiro de Software Full Stack",
    dataPublicacao: "15/05/2026",
    dataAplicacao: "01/06/2026",
    status: "Enviada",
    localizacao: "São Paulo, SP (Híbrido)",
    salario: "R$ 10.500/mês",
    descricao:
      "Atuar na modernização dos canais digitais de atendimento ao cliente, migrando o monolith para serviços distribuídos.",
    requisitos: ["Java/Spring Boot", "Angular ou React", "Kafka", "AWS"],
    feedback: "Inscrição confirmada.",
  },
  {
    id: "17",
    empresa: "ByteDance (TikTok)",
    cargo: "Frontend Engineer",
    dataPublicacao: "06/06/2026",
    dataAplicacao: null,
    status: "Vaga Divulgada",
    localizacao: "São Paulo, SP",
    salario: "R$ 14.000/mês",
    descricao:
      "Manutenção e criação de ferramentas internas para os criadores de conteúdo da plataforma LATAM.",
    requisitos: [
      "React",
      "Gerenciamento de Estado Complexo",
      "Otimização de Renderização",
      "Inglês Fluente",
    ],
    feedback: "Vaga de alta concorrência. Aplique agora.",
  },
];

export default dadosCandidaturas;
